# Generated by Django 6.0.2 on 2026-02-21 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='action',
            field=models.CharField(choices=[('ask', 'Ask'), ('generate', 'Generate')], default='generate', max_length=10),
        ),
        migrations.AddField(
            model_name='message',
            name='questions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
